### ISSUE TITLE
Please update lru-cache

### ISSUE THREAD

**Issue by SimonSchick** [mysqljs/named-placeholders#12]
It causes some duplication in downstream dependencies :)

**Comment by SimonSchick** [comment]
@sidorares mind doing a release here? :)

**Comment by sidorares** [comment]
oh. Will do now

**Comment by sidorares** [comment]
v1.1.2

**Comment by SimonSchick** [comment]
woop woop

**Comment by SimonSchick** [comment]
On that note, this should've been a major release 😓

**Comment by xuxucode** [comment]
Please update lru-cache to 6.0.0
